### PR TITLE
Kill scope api and clean up

### PR DESCRIPTION
**Pull request by mariogrip**
This kills the scope api part, and also does some cleanups

### CODE REVIEW

**Review by dobey — CHANGES_REQUESTED** [review]
This breaks API/ABI, so I think we need to bump the soname, rename the binary package for the lib, and will need to rebuild anything which depends on it (thumbnailer seems to be the only thing other than scopes stuff at least).

**Comment by mariogrip** [comment]
> This breaks API/ABI, so I think we need to bump the soname, rename the binary package for the lib, and will need to rebuild anything which depends on it (thumbnailer seems to be the only thing other than scopes stuff at least).

Ok bumped the soname, but why would we need to rename the binary package?

I'll also remove anything that depends on it

**Comment by mariogrip** [comment]
One thing that we might do is up the soname on the debian packaging also.

**Comment by dobey** [comment]
> Ok bumped the soname, but why would we need to rename the binary package?

You only bumped the micro number in the API version string. I think you need to bump the `UNITY_API_VERSION` variable in `src/CMakeLists.txt` to be `1` instead. And the binary package, as per Debian Policy, includes the SO version in the name (`libunity-api0` in this case), so when the binary version changes, the binary package name for the library, has to change with it.

**Comment by mariogrip** [comment]
> > Ok bumped the soname, but why would we need to rename the binary package?
> 
> You only bumped the micro number in the API version string. I think you need to bump the `UNITY_API_VERSION` variable in `src/CMakeLists.txt` to be `1` instead. And the binary package, as per Debian Policy, includes the SO version in the name (`libunity-api0` in this case), so when the binary version changes, the binary package name for the library, has to change with it.

Ah i see, we did change a cpp file (version.cpp), I thought it was only headers. will update the soname

**Comment by mariogrip** [comment]
There i think we should be ok

**Review by dobey — APPROVED** [review]

**Pull request merged**
